### PR TITLE
Added Kit Anchor

### PR DESCRIPTION
**Pull request by Hotkeyyy**

### CODE REVIEW

**Comment by copyandexecute** [comment]
Event not registered in Constructor with addEvents()
Use Attribute.KNOCKBACK_RESISTANCE or smth like that rather than canceling the event

**Comment by Hotkeyyy** [comment]
I changed Anchor and use the Attributes

**Comment by copyandexecute** [comment]
Override methods disable() and enable() so rogue can disable Anchor (You have to set the modifier there)
due to this you only have to set the KB of the hitted entity but ALL living entities should be included not just players

Dont call uper.onPlayerAttacksLivingEntity(event, attacker, entity);

**Comment by Hotkeyyy** [comment]
I added the disable method

**Comment by copyandexecute** [comment]
Why would set and remove the attribute of the anchor himself everytime?

Just override enable() and set the attribute there.

**Comment by Hotkeyyy** [comment]
I think it's right but I don't know exactly what you mean

**Pull request closed without merging**
