### PR TITLE
Add gravedigger

### PR DESCRIPTION
**Pull request by Maquzowastaken**
**KitItem**: Null
**Cooldown:** Null
**Name**: GraveDigger
**DisplayItem**: Stone shovel

Explenation:

_Shulker mode_ (normal):
When you kill an enemy you will get a shulker box with his inventory.
also you get the ABSORPTION effect

_Chest mode_: 
When you kill an enemy a chest will spawn at his location with his loot in It.
The chest will explode after 45 seconds

_Note for changing mode: 0 = true 1 = false_

**For Royzer (Important)**
Nullpointer at: 315 and 196
Feast:  Normal loot in box/chest until Feast fixed. line: 165 and 292

### CODE REVIEW

**Comment by r0yzer** [comment]
junge ich bin bei der formatierung gestorben kennst du strg + alt + l

**Comment by Maquzowastaken** [comment]
Ja mach ich immer

**Comment by Maquzowastaken** [comment]
Geht doch noch

**Comment by r0yzer** [comment]
#207 :joy;: moment

**Pull request closed without merging**
